title: SFF Maker
description: > # This is a multiline description
  A site dedicated to SFF (Science Fiction & Fantasy) making. 
  Explore content and resources related to creating amazing SFF works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Settings for GitHub Pages
markdown: kramdown

# Build settings
theme: minima
